"""Eval-only twins of the KITTI IA-SSD oracles for part B of experiments_md 20261011_07 (ANALYSIS): the arms of the KITTI
target-oracle degradation table (20261011_02, `make_kitti_sensitivity_configs.ARMS`), adapted to a fixed point budget.

Each twin is `_BASE_CONFIG_: <oracle config>` plus changes in the EVALUATED block only (DATA_CONFIG_TAR when the config has
one, else DATA_CONFIG, as test.py reads them). Two arms differ from the CenterPoint generator on purpose:
  - density dose: the uniform `sample_points` RATIO step goes right BEFORE the budget `sample_points` (16,384). The shared
    helper `with_ratio` inserts it before `transform_points_to_voxels`, which an IA-SSD config does not have, so on IA-SSD
    it would be a silent no-op;
  - vertical-FOV cut: SENSOR_ORIGIN = the block's own SHIFT_COOR (27600's published recipe has none, so [0, 0, 0]; the
    family oracle 27569 has [0, 0, 1.7]).
The thin arms (EVAL_RING_THIN: lines, columns, the 0.332-deg bin, their count-matched random controls, the HDL-32E render)
are the CenterPoint generator's, unchanged. `--check` resolves every twin and passes only if nothing outside the evaluated
block differs from its oracle and the block changed in exactly the intended keys.

    python analysis/make_iassd_sensitivity_configs.py [--check]
"""
import sys
from pathlib import Path

import yaml

sys.path.insert(0, '.')
from analysis.make_kitti_sensitivity_configs import ARMS  # noqa: E402  (imports _init_path)
from analysis.make_kitti_sensitivity_configs import tar_change as kitti_change  # noqa: E402
from analysis.make_sensitivity_configs import resolved  # noqa: E402

OUT = Path('cfgs/da-ieee-access-analysis/sensitivity-iassd')
BASES = ['cfgs/da-ieee-access-pointrcnn/iassd-published-kitti.yaml',          # 27600: published recipe, FOV-cropped
         'cfgs/da-ieee-access-pointrcnn/iassd-sourceonly-kitti2kitti.yaml']   # 27569: family protocol, 360 deg


def with_ratio_before_budget(processors, r):
    out, done = [], False
    for p in processors:
        if p['NAME'] == 'sample_points' and p['NUM_POINTS']['test'] != -1 and not done:
            out.append({'NAME': 'sample_points', 'NUM_POINTS': {'train': -1, 'test': -1}, 'RATIO': {'test': r}})
            done = True
        out.append(dict(p))
    assert done, 'no budget sample_points step to put the density dose in front of'
    return out


def block_change(blk, kind, val):
    if kind == 'ratio':
        return {'DATA_PROCESSOR': with_ratio_before_budget(blk['DATA_PROCESSOR'], val)}, 'ratio%03d' % int(round(val * 100))
    if kind == 'elev':
        side, _, deg = val.partition(':')
        step = {'NAME': 'mask_points_by_spec', 'SENSOR_ORIGIN': list(blk.get('SHIFT_COOR') or [0.0, 0.0, 0.0]),
                ('ELEVATION_MAX_DEG' if side == 'max' else 'ELEVATION_MIN_DEG'): float(deg)}
        return {'DATA_PROCESSOR': [step] + blk['DATA_PROCESSOR']}, 'el' + side + deg.replace('-', 'm').replace('.', 'p')
    return kitti_change(blk, kind, val)


def main(check=False):
    OUT.mkdir(parents=True, exist_ok=True)
    ok_all = True
    for base in BASES:
        base_path = Path(base)
        rb = resolved(base_path)
        key = 'DATA_CONFIG_TAR' if rb.get('DATA_CONFIG_TAR') else 'DATA_CONFIG'
        blk = rb[key]
        assert blk['DATASET'] == 'KittiDataset'
        for kind, val in ARMS:
            change, tag = block_change(blk, kind, val)
            child = OUT / f'{base_path.stem}-{tag}.yaml'
            if not check:
                header = (f'# EVAL-ONLY twin of {base_path} for experiments_md 20261011_07 part B ({tag}): {key} change only.\n'
                          f'# Generated by analysis/make_iassd_sensitivity_configs.py. ANALYSIS.\n')
                child.write_text(header + yaml.safe_dump({'_BASE_CONFIG_': str(base_path), key: change},
                                                         sort_keys=False, default_flow_style=None))
            rc = resolved(child)
            diffs = [k for k in set(rb) | set(rc) if k not in (key, '_BASE_CONFIG_') and rb.get(k) != rc.get(k)]
            cb = rc[key]
            changed = sorted(k for k in set(blk) | set(cb) if blk.get(k) != cb.get(k) and k != '_BASE_CONFIG_')
            ok = not diffs and set(changed) == set(change)
            ok_all &= ok
            print(f'{child.name}: {"OK" if ok else "DIFF " + str(diffs) + str(changed)}  changed={changed}')
    sys.exit(0 if ok_all else 1)


if __name__ == '__main__':
    main(check='--check' in sys.argv)
