"""Write the eval-only sensor-spec-cut twins for experiments_md 20261008_05 (hypotheses H2 / H6 / H10).

Each twin is `_BASE_CONFIG_: <as-scored eval config>` plus ONE change in DATA_CONFIG_TAR: a
`mask_points_by_spec` step prepended to the target's DATA_PROCESSOR (the list is copied from the
resolved base, since lists do not merge), or `LIDAR_INDICES: [0]` for the TOP-only cut. Every value
is a published spec: Waymo TOP at (1.43, 0, 2.184) in the vehicle frame, top beam +2.4 deg, bottom
beam -17.6 deg; nuScenes LIDAR_TOP at (0, 0, 1.75) after SHIFT_COOR, ego-removal radius 1.5 m.
ANALYSIS: the cuts are applied to the evaluation target only.

    python analysis/make_speccut_configs.py          # writes tools/cfgs/da-ieee-access-analysis/speccut/*.yaml
    python analysis/make_speccut_configs.py --check  # resolved diff of every twin against its base
"""
import sys
from pathlib import Path
import yaml
from easydict import EasyDict
sys.path.insert(0, '.')
import _init_path  # noqa
from pcdet.config import cfg_from_yaml_file

OUT = Path('cfgs/da-ieee-access-analysis/speccut')
WAYMO_ORIGIN = [1.43, 0.0, 2.184]
NUSC_ORIGIN = [0.0, 0.0, 1.75]
# base eval config -> (target, model tag)
BASES = {
    'waymo': ['centerpoint-gblobs-accum-legaldepth-st3d-nuscenes2waymo', 'centerpoint-gblobs-sourceonly-nuscenes2waymo',
              'centerpoint-accum-legaldepth-nuscenes2waymo', 'centerpoint-sourceonly-waymo2waymo'],
    'nuscenes': ['centerpoint-sourceonly-waymo', 'centerpoint-global-waymo2nuscenes',
                 'centerpoint-gblobs-sourceonly-waymo', 'centerpoint-sourceonly-nuscenes'],
}
CUTS = {
    'waymo': {
        'toponly': {'LIDAR_INDICES': [0]},                                                     # H2
        'ego15': {'STEP': dict(SENSOR_ORIGIN=WAYMO_ORIGIN, MIN_RADIUS_M=1.5)},                  # H10 (Waymo side)
    },
    'nuscenes': {
        'elmax24': {'STEP': dict(SENSOR_ORIGIN=NUSC_ORIGIN, ELEVATION_MAX_DEG=2.4)},            # H6
        'elmin176': {'STEP': dict(SENSOR_ORIGIN=NUSC_ORIGIN, ELEVATION_MIN_DEG=-17.6)},         # H10 (nuScenes side)
    },
}


def plain(o):
    if isinstance(o, dict):
        return {k: plain(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [plain(v) for v in o]
    return o


def resolved(path):
    cfg = EasyDict(); cfg_from_yaml_file(str(path), cfg); return plain(cfg)


def main(check=False):
    OUT.mkdir(parents=True, exist_ok=True)
    for target, bases in BASES.items():
        for base in bases:
            base_path = Path('cfgs/da-ieee-access') / f'{base}.yaml'
            rb = resolved(base_path)
            for cut, spec in CUTS[target].items():
                tar = {}
                if 'LIDAR_INDICES' in spec:
                    tar['LIDAR_INDICES'] = spec['LIDAR_INDICES']
                else:
                    step = {'NAME': 'mask_points_by_spec', **spec['STEP']}
                    tar['DATA_PROCESSOR'] = [step] + rb['DATA_CONFIG_TAR']['DATA_PROCESSOR']
                child = OUT / f'{base}-{cut}.yaml'
                if not check:
                    header = (f'# EVAL-ONLY twin of {base_path} for experiments_md 20261008_05 ({cut}): one target-side\n'
                              f'# sensor-spec cut, nothing else. Generated by analysis/make_speccut_configs.py. ANALYSIS.\n')
                    body = {'_BASE_CONFIG_': str(base_path), 'DATA_CONFIG_TAR': tar}
                    child.write_text(header + yaml.safe_dump(body, sort_keys=False, default_flow_style=None))
                rc = resolved(child)
                # diff: everything equal except DATA_CONFIG_TAR's one change
                diffs = []
                for k in set(rb) | set(rc):
                    if k in ('DATA_CONFIG_TAR', '_BASE_CONFIG_'):
                        continue
                    if rb.get(k) != rc.get(k):
                        diffs.append(k)
                tb, tc = dict(rb['DATA_CONFIG_TAR']), dict(rc['DATA_CONFIG_TAR'])
                changed = sorted(k for k in set(tb) | set(tc) if tb.get(k) != tc.get(k) and k != '_BASE_CONFIG_')
                exp = ['LIDAR_INDICES'] if 'LIDAR_INDICES' in spec else ['DATA_PROCESSOR']
                ok = not diffs and changed == exp and (
                    'LIDAR_INDICES' in spec or tc['DATA_PROCESSOR'][1:] == tb['DATA_PROCESSOR'])
                print(f'{child.name}: {"OK" if ok else "DIFF " + str(diffs) + str(changed)}')


if __name__ == '__main__':
    main(check='--check' in sys.argv)
