"""Eval-only twins for experiments_md 20261010_03: test-time TARGET accumulation on further dense -> sparse pairs with a
nuScenes target (Lyft, PandaSet, KITTI sources), each pair read independently against its own pre-declared depth.

Same mechanism as make_sensitivity_configs.py's accumulation twins (20261010_01 A), copied rather than imported so this
file does not depend on that one's working tree:
  - `_BASE_CONFIG_: <as-scored config>` plus DATA_CONFIG_TAR changes only: MAX_SWEEPS N, the test voxel cap raised so no
    accumulated point is dropped, and for N > 10 the 200-sweep val infos (keyframe chaining);
  - box-based motion compensation never runs at evaluation (should_compensate requires training), so no label is read.
`--check` resolves every twin and passes only if nothing outside DATA_CONFIG_TAR differs from its base.

The depths are the label-free rule's (analysis/accumulation_deep_nuscenes.py, global radial parity of nuScenes TRAIN
clouds against the source's single-frame density, per nuScenes platform); they are pre-declared in 20261010_03 §2.

    python analysis/make_target_accum_configs.py [--check] [--voxel_cap N]
"""
import sys
from pathlib import Path

import yaml
from easydict import EasyDict

sys.path.insert(0, '.')
import _init_path  # noqa
from pcdet.config import cfg_from_yaml_file

OUT = Path('cfgs/da-ieee-access-analysis/sensitivity')
CAP = int(sys.argv[sys.argv.index('--voxel_cap') + 1]) if '--voxel_cap' in sys.argv else 600000
# as-scored config -> target MAX_SWEEPS doses (20261010_03 §2)
TWINS = {
    'centerpoint-sourceonly-lyft': [10, 15, 30],          # Lyft (both platforms): Boston 30 / Singapore 15 -> 15
    'centerpoint-gblobs-sourceonly-lyft': [15],
    'centerpoint-sourceonly-pandaset': [10, 20, 50],      # Pandar64: Boston 50 / Singapore 20 -> 20
    'centerpoint-sourceonly-kitti': [10, 15],             # KITTI: Boston 15 / Singapore 10 -> 10
}


def plain(o):
    if isinstance(o, dict):
        return {k: plain(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [plain(v) for v in o]
    return o


def resolved(path):
    cfg = EasyDict(); cfg_from_yaml_file(str(path), cfg); return plain(cfg)


def with_cap(processors, cap):
    out = []
    for p in processors:
        p = dict(p)
        if p['NAME'] == 'transform_points_to_voxels':
            p['MAX_NUMBER_OF_VOXELS'] = {**p['MAX_NUMBER_OF_VOXELS'], 'test': cap}
        out.append(p)
    return out


def tar_change(tb, n):
    assert tb['DATASET'] == 'NuScenesDataset', tb['DATASET']
    tar = {'MAX_SWEEPS': n, 'DATA_PROCESSOR': with_cap(tb['DATA_PROCESSOR'], CAP)}
    if n > 10:
        tar['INFO_PATH'] = {**tb['INFO_PATH'], 'test': ['nuscenes_infos_200sweeps_val.pkl']}
    return tar


def main(check=False):
    OUT.mkdir(parents=True, exist_ok=True)
    bad = 0
    for base, depths in TWINS.items():
        base_path = Path('cfgs/da-ieee-access') / f'{base}.yaml'
        rb = resolved(base_path)
        for n in depths:
            tar = tar_change(rb['DATA_CONFIG_TAR'], n)
            child = OUT / f'{base}-acc{n}.yaml'
            if not check:
                header = (f'# EVAL-ONLY twin of {base_path} for experiments_md 20261010_03 (nuScenes target accumulated to '
                          f'{n} sweeps at test time, ego motion only): target-side change only.\n'
                          f'# Generated by analysis/make_target_accum_configs.py (test voxel cap {CAP}).\n')
                child.write_text(header + yaml.safe_dump({'_BASE_CONFIG_': str(base_path), 'DATA_CONFIG_TAR': tar},
                                                         sort_keys=False, default_flow_style=None))
            rc = resolved(child)
            diffs = [k for k in set(rb) | set(rc) if k not in ('DATA_CONFIG_TAR', '_BASE_CONFIG_') and rb.get(k) != rc.get(k)]
            tb, tc = rb['DATA_CONFIG_TAR'], rc['DATA_CONFIG_TAR']
            changed = sorted(k for k in set(tb) | set(tc) if tb.get(k) != tc.get(k) and k != '_BASE_CONFIG_')
            ok = not diffs and set(changed) == set(tar) and tc['MAX_SWEEPS'] == n
            bad += not ok
            print(f'{child.name}: {"OK" if ok else "DIFF " + str(diffs) + str(changed)}  changed={changed}')
    sys.exit(1 if bad else 0)


if __name__ == '__main__':
    main(check='--check' in sys.argv)
