"""Eval-only twins for experiments_md 20261011_03: the PandaSet target-oracle degradation table, the PandaSet extension
of 20261010_01 §3 (make_sensitivity_configs.py made the Waymo / nuScenes twins). ANALYSIS.

Each twin is `_BASE_CONFIG_: <oracle config>` plus changes in DATA_CONFIG_TAR only:
  - ratio: a `sample_points` step with RATIO {'test': r} before voxelisation (uniform random keep);
  - thin: EVAL_RING_THIN on the Pandar64's recovered channels (pandaset_rings.eval_thin_mask) - lines or columns cut,
    one point per channel per azimuth bin, their count-matched random controls, channel-elevation (vertical field of
    view) cuts, and the nuScenes HDL-32E render (27807's rule at evaluation);
  - acc: MAX_SWEEPS N (neighbouring annotated frames in the anchor's pose; box motion compensation never runs at
    evaluation), with the test voxel cap raised so accumulated points are never dropped.
`--check` resolves every twin and passes only if nothing outside DATA_CONFIG_TAR differs from its base.

    python analysis/make_pandaset_sensitivity_configs.py [--check]
"""
import sys
from pathlib import Path

import yaml
from easydict import EasyDict

sys.path.insert(0, '.')
import _init_path  # noqa
from pcdet.config import cfg_from_yaml_file

OUT = Path('cfgs/da-ieee-access-analysis/sensitivity-pandaset')
CAP = 600000
CACHE = '/home/koyama/data/pandaset_rings/v1'
HDL32E = {'SPACING_DEG': 1.33, 'AZ_RES_DEG': 0.332, 'TARGET_FOV_DEG': [-30.67, 10.67]}
TWINS = {
    # spin oracle: Pandar64 -> Pandar64 (26389's epoch 115, scored 360 deg by 26971)
    'centerpoint-pandaset-spin2spin': [
        ('ratio', 0.75), ('ratio', 0.5), ('ratio', 0.25),
        ('thin', 'rows'), ('thin', 'random'), ('thin', 'cols'), ('thin', 'random_cols'),
        ('thin', 'cols:4'), ('thin', 'random_cols:4'), ('thin', 'azbin:0.332'), ('thin', 'random_azbin:0.332'),
        ('thin', 'elmax:0'), ('thin', 'elmax:-3'), ('thin', 'elmin:-14'), ('thin', 'elmin:-10'),
        ('thin', 'pattern:hdl32e'), ('acc', 3), ('acc', 7)],
    # flash oracle: PandarGT -> PandarGT (26974's 15-epoch checkpoint, scored in the cone); no channels, so no thin arms
    'centerpoint-pandaset-flash2flash': [('ratio', 0.75), ('ratio', 0.5), ('ratio', 0.25), ('acc', 3), ('acc', 7)],
}


def plain(o):
    if isinstance(o, dict):
        return {k: plain(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [plain(v) for v in o]
    return o


def resolved(path):
    cfg = EasyDict(); cfg_from_yaml_file(str(path), cfg); return plain(cfg)


def with_cap(processors, cap):
    out = []
    for p in processors:
        p = dict(p)
        if p['NAME'] == 'transform_points_to_voxels':
            p['MAX_NUMBER_OF_VOXELS'] = {**p['MAX_NUMBER_OF_VOXELS'], 'test': cap}
        out.append(p)
    return out


def with_ratio(processors, r):
    out = []
    for p in processors:
        if p['NAME'] == 'transform_points_to_voxels':
            out.append({'NAME': 'sample_points', 'NUM_POINTS': {'train': -1, 'test': -1}, 'RATIO': {'test': r}})
        out.append(dict(p))
    return out


def tar_change(rb, kind, val):
    tb = rb['DATA_CONFIG_TAR']
    if kind == 'acc':
        return {'MAX_SWEEPS': val, 'DATA_PROCESSOR': with_cap(tb['DATA_PROCESSOR'], CAP)}, f'acc{val}'
    if kind == 'ratio':
        return {'DATA_PROCESSOR': with_ratio(tb['DATA_PROCESSOR'], val)}, 'ratio%03d' % int(round(val * 100))
    if kind == 'thin':
        assert tb.get('LIDAR_DEVICE', 0) == 0, 'channel labels exist for the Pandar64 only'
        mode, _, par = val.partition(':')
        cut = {'LABEL_CACHE': CACHE, 'MODE': mode}
        if mode.endswith('cols') or mode in ('rows', 'random'):
            cut['STRIDE'] = int(par) if par else 2
        if mode.endswith('azbin'):
            cut['AZ_RES_DEG'] = float(par)
        if mode in ('elmax', 'elmin'):
            cut['EL_DEG'] = float(par)
        if mode == 'pattern':
            assert par == 'hdl32e'
            cut.update(HDL32E)
        suffix = mode.replace('_', '') + (par.replace('.', 'p').replace('-', 'm') if par else '')
        return {'EVAL_RING_THIN': cut}, 'ring' + suffix
    raise ValueError(kind)


def main(check=False):
    OUT.mkdir(parents=True, exist_ok=True)
    ok_all = True
    for base, arms in TWINS.items():
        base_path = Path('cfgs/da-ieee-access') / f'{base}.yaml'
        rb = resolved(base_path)
        for kind, val in arms:
            tar, tag = tar_change(rb, kind, val)
            child = OUT / f'{base}-{tag}.yaml'
            if not check:
                header = (f'# EVAL-ONLY twin of {base_path} for experiments_md 20261011_03 ({tag}): target-side change only.\n'
                          f'# Generated by analysis/make_pandaset_sensitivity_configs.py. ANALYSIS.\n')
                child.write_text(header + yaml.safe_dump({'_BASE_CONFIG_': str(base_path), 'DATA_CONFIG_TAR': tar},
                                                         sort_keys=False, default_flow_style=None))
            rc = resolved(child)
            diffs = [k for k in set(rb) | set(rc) if k not in ('DATA_CONFIG_TAR', '_BASE_CONFIG_') and rb.get(k) != rc.get(k)]
            tb, tc = rb['DATA_CONFIG_TAR'], rc['DATA_CONFIG_TAR']
            changed = sorted(k for k in set(tb) | set(tc) if tb.get(k) != tc.get(k) and k != '_BASE_CONFIG_')
            ok = not diffs and set(changed) == set(tar)
            ok_all &= ok
            print(f'{child.name}: {"OK" if ok else "DIFF " + str(diffs) + str(changed)}  changed={changed}')
    print('ALL OK' if ok_all else 'SOME DIFFER')


if __name__ == '__main__':
    main(check='--check' in sys.argv)
