"""Eval-only twins of the KITTI in-domain oracle for the KITTI arm of the target-oracle degradation table
(experiments_md 20261011_02). ANALYSIS. Same construction as make_sensitivity_configs.py (20261010_01 §3), whose
helpers it reuses: each twin is `_BASE_CONFIG_: <oracle config>` plus changes in DATA_CONFIG_TAR only.

  - density dose: `sample_points` RATIO {'test': r} before voxelisation (uniform random keep);
  - thin: EVAL_RING_THIN on the KITTI loader (rings from the stored order, kitti_rings.py) - lines every 2nd / 3rd /
    4th ring (64 -> 32 / 21 / 16, LiDAR Distillation's integer decimations), columns every 2nd / 4th return, one point per
    line per 0.332-deg bin, each with its count-matched random control, and the nuScenes HDL-32E render (27807's rule);
  - elev: vertical field of view cut about the KITTI velodyne at [0, 0, 1.70] (SHIFT_COOR applied), the same absolute
    cuts as the Waymo / nuScenes oracles, plus Waymo TOP's lower edge (-17.6 deg).
KITTI has no sequences, so there is no accumulation arm. The oracle is x,y,z only, so there is no intensity arm.
`--check` resolves every twin and passes only if nothing outside DATA_CONFIG_TAR differs from the oracle.

    python analysis/make_kitti_sensitivity_configs.py [--check]
"""
import sys
from pathlib import Path

import yaml

sys.path.insert(0, '.')
from analysis.make_sensitivity_configs import resolved, with_ratio  # noqa: E402  (imports _init_path)

OUT = Path('cfgs/da-ieee-access-analysis/sensitivity')
BASE = 'centerpoint-sourceonly-kitti2kitti-noros-zshift'   # 26843, the Table C ceiling (80.33 / 70.59 moderate)
KITTI_SENSOR = [0.0, 0.0, 1.70]
ARMS = [('ratio', 0.75), ('ratio', 0.5), ('ratio', 0.25),
        ('thin', 'rows:2'), ('thin', 'random:2'), ('thin', 'rows:3'), ('thin', 'random:3'),
        ('thin', 'rows:4'), ('thin', 'random:4'),
        ('thin', 'cols:2'), ('thin', 'random_cols:2'), ('thin', 'cols:4'), ('thin', 'random_cols:4'),
        ('thin', 'azbin:0.332'), ('thin', 'random_azbin:0.332'),
        ('thin', 'pattern:hdl32e'),
        ('elev', 'max:0'), ('elev', 'max:-3'), ('elev', 'min:-14'), ('elev', 'min:-10'), ('elev', 'min:-17.6')]


def tar_change(tb, kind, val):
    if kind == 'ratio':
        return {'DATA_PROCESSOR': with_ratio(tb['DATA_PROCESSOR'], val)}, 'ratio%03d' % int(round(val * 100))
    if kind == 'thin':
        mode, _, par = val.partition(':')
        if mode == 'pattern':
            assert par == 'hdl32e'
            return {'EVAL_RING_THIN': {'MODE': 'pattern', 'SPACING_DEG': 1.33, 'AZ_RES_DEG': 0.332}}, 'ringpatternhdl32e'
        if mode.endswith('azbin'):
            return {'EVAL_RING_THIN': {'MODE': mode, 'AZ_RES_DEG': float(par)}}, 'ring' + mode.replace('_', '') + par.replace('.', 'p')
        return {'EVAL_RING_THIN': {'MODE': mode, 'STRIDE': int(par)}}, 'ring' + mode.replace('_', '') + par
    if kind == 'elev':
        side, _, deg = val.partition(':')
        step = {'NAME': 'mask_points_by_spec', 'SENSOR_ORIGIN': KITTI_SENSOR,
                ('ELEVATION_MAX_DEG' if side == 'max' else 'ELEVATION_MIN_DEG'): float(deg)}
        return {'DATA_PROCESSOR': [step] + tb['DATA_PROCESSOR']}, 'el' + side + deg.replace('-', 'm').replace('.', 'p')
    raise ValueError(kind)


def main(check=False):
    OUT.mkdir(parents=True, exist_ok=True)
    base_path = Path('cfgs/da-ieee-access') / f'{BASE}.yaml'
    rb = resolved(base_path)
    assert rb['DATA_CONFIG_TAR']['DATASET'] == 'KittiDataset'
    assert rb['DATA_CONFIG_TAR'].get('SHIFT_COOR') == KITTI_SENSOR, rb['DATA_CONFIG_TAR'].get('SHIFT_COOR')
    ok_all = True
    for kind, val in ARMS:
        tar, tag = tar_change(rb['DATA_CONFIG_TAR'], kind, val)
        child = OUT / f'{BASE}-{tag}.yaml'
        if not check:
            header = (f'# EVAL-ONLY twin of {base_path} for experiments_md 20261011_02 ({tag}): target-side change only.\n'
                      f'# Generated by analysis/make_kitti_sensitivity_configs.py. ANALYSIS.\n')
            child.write_text(header + yaml.safe_dump({'_BASE_CONFIG_': str(base_path), 'DATA_CONFIG_TAR': tar},
                                                     sort_keys=False, default_flow_style=None))
        rc = resolved(child)
        diffs = [k for k in set(rb) | set(rc) if k not in ('DATA_CONFIG_TAR', '_BASE_CONFIG_') and rb.get(k) != rc.get(k)]
        tb, tc = rb['DATA_CONFIG_TAR'], rc['DATA_CONFIG_TAR']
        changed = sorted(k for k in set(tb) | set(tc) if tb.get(k) != tc.get(k) and k != '_BASE_CONFIG_')
        ok = not diffs and set(changed) == set(tar)
        ok_all &= ok
        print(f'{child.name}: {"OK" if ok else "DIFF " + str(diffs) + str(changed)}  changed={changed}')
    sys.exit(0 if ok_all else 1)


if __name__ == '__main__':
    main(check='--check' in sys.argv)
