"""Shared score bins for the pseudo-label threshold analysis.

The stored pseudo-labels of a training run start at NEG_THRESH (0.1), so every script here was
written with bins from 0.10. A file generated by generate_pseudo_labels.py at --thresh 0.0001
carries the whole distribution; set FULL_RANGE=1 to extend every bin list downward without
touching the 0.10+ bins, so tables stay comparable row for row.

PS_LABEL points the scripts that read the pickle directly (persistence.py, gaps.py) at a file;
the default is the run the 20260926_06 report analysed.
"""
import os
import numpy as np

FULL = os.environ.get('FULL_RANGE') == '1'
PS_LABEL = os.environ.get(
    'PS_LABEL', '/storage/wandb/run-20260926_102950-uq83obp7/files/ps_label/ps_label_e0.pkl')
LO = 0.027 if FULL else 0.10   # the teacher's heatmap floor: sigmoid of the background logit, ~0.04; 0.027 min at K=2000
LOW_SB = [.027, .04, .05, .06, .07, .08, .09] if FULL else []
LOW_T = [.027, .05, .07] if FULL else []
LOW_GRID = [.027, .03, .04, .05, .06, .07, .08, .09] if FULL else []

SB = LOW_SB + [.10, .12, .14, .16, .18, .20, .25, .30, .40, .50, 1.01]          # slice edges
T = LOW_T + [.10, .15, .20, .25, .30, .40, .50]                                  # cumulative cuts
GRID = np.round(np.concatenate([LOW_GRID, np.arange(0.10, 0.601, 0.01)]), 4)     # search grid
BOTTOM = (LO, 0.05) if FULL else (0.10, 0.12)                                    # "lowest slice" anchor
NCOMP = 3 if FULL else 2   # full range shows three regimes: background plateau, low-confidence tail, confident mode
