"""Write a FLAT config that points a self-training config's TARGET slot at another dataset's val split.

Purpose: run the same frozen teacher over the labelled SOURCE's validation set, so its selection
bias (points per kept box over points per GT box, per range ring, as a function of the score cut)
can be measured with source labels only, then transferred to the target - see
experiments_md/20260927_01 section 5 and the follow-up on per-range thresholds.

Why flat: `_fill_missing_from_base` merges nested dicts key by key, so a child that redeclares
`DATA_CONFIG_TAR` with a different `_BASE_CONFIG_` still inherits every nuScenes key it does not
spell out. Resolving both files with the repo's own loader and dumping the result avoids that.

    python analysis/pseudo_label_threshold/make_teacher_on_source_val_cfg.py \
        --cfg_file cfgs/da-ieee-access/centerpoint-foreground-lyft2nuscenes.yaml \
        --dataset_cfg cfgs/da-ieee-access/da_lyft_dataset.yaml \
        --out analysis/pseudo_label_threshold/cfgs/teacher_on_lyft_val.yaml
"""
import argparse
import sys
from pathlib import Path

import yaml
from easydict import EasyDict

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import _init_path  # noqa: F401
from pcdet.config import cfg_from_yaml_file


def plain(o):
    if isinstance(o, dict):
        return {k: plain(v) for k, v in o.items() if k != '_BASE_CONFIG_'}
    if isinstance(o, (list, tuple)):
        return [plain(v) for v in o]
    return o


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cfg_file', required=True)
    ap.add_argument('--dataset_cfg', required=True)
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    full = cfg_from_yaml_file(args.cfg_file, EasyDict())
    ds = cfg_from_yaml_file(args.dataset_cfg, EasyDict())
    val_infos = list(ds.INFO_PATH['test'])
    ds.DATA_SPLIT = {'train': 'val', 'test': 'val'}
    ds.INFO_PATH = {'train': val_infos, 'test': val_infos}
    ds.USE_PSEUDO_LABEL = True
    full.DATA_CONFIG_TAR = ds
    out = plain(full)
    header = ('# GENERATED by make_teacher_on_source_val_cfg.py - do not edit or train with.\n'
              '# %s with DATA_CONFIG_TAR replaced by %s on its VAL split, for a teacher pass over\n'
              '# labelled source data (selection-bias measurement, 20260927_01 follow-up).\n'
              % (args.cfg_file, args.dataset_cfg))
    with open(args.out, 'w') as f:
        f.write(header)
        yaml.safe_dump(out, f, sort_keys=False, default_flow_style=False)
    print('wrote', args.out)
    print('DATA_CONFIG_TAR:', out['DATA_CONFIG_TAR']['DATASET'], out['DATA_CONFIG_TAR']['INFO_PATH'],
          'SHIFT_COOR', out['DATA_CONFIG_TAR'].get('SHIFT_COOR'))


if __name__ == '__main__':
    main()
